// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuscleUp.DataBase;

#nullable disable

namespace MuscleUp.DataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608144706_MigrationAdicionandoDificuldadeDoTreino")]
    partial class MigrationAdicionandoDificuldadeDoTreino
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MuscleUp.Dominio.Academias.Academia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Numero")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Academias");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Alunos.Aluno", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("ProblemasMedicos")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Exercicios.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<int>("GrupoMuscular")
                        .HasColumnType("int");

                    b.Property<int?>("IdAcademia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdAcademia");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Exercicios.ExercicioDoTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdExercicio")
                        .HasColumnType("int");

                    b.Property<int>("IdMembroTrabalhado")
                        .HasColumnType("int");

                    b.Property<int>("Repeticao")
                        .HasColumnType("int");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdExercicio");

                    b.HasIndex("IdMembroTrabalhado");

                    b.ToTable("ExerciciosDoTreino", (string)null);
                });

            modelBuilder.Entity("MuscleUp.Dominio.GruposMuscularesTrabalhados.GrupoMuscularTrabalhado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DivisaoDeTreino")
                        .HasColumnType("int");

                    b.Property<int>("GrupoMuscular")
                        .HasColumnType("int");

                    b.Property<int>("IdTreino")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdTreino");

                    b.ToTable("GruposMuscularesTrabalhados", (string)null);
                });

            modelBuilder.Entity("MuscleUp.Dominio.Treinos.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DificuldadeDoTreino")
                        .HasColumnType("int");

                    b.Property<int>("Divisao")
                        .HasColumnType("int");

                    b.Property<int>("IdAcademia")
                        .HasColumnType("int");

                    b.Property<int?>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfessor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("Publico")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Tempo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("IdAcademia");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdProfessor");

                    b.ToTable("Treinos", (string)null);
                });

            modelBuilder.Entity("MuscleUp.Dominio.Treinos.TreinoPublicoEDestinadoDoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int?>("IdProfessorQueDestinou")
                        .HasColumnType("int");

                    b.Property<int>("IdTreino")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdProfessorQueDestinou");

                    b.HasIndex("IdTreino");

                    b.ToTable("TreinosPublicosEDestinadosDoAluno", (string)null);
                });

            modelBuilder.Entity("MuscleUp.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("IdAcademia")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdAcademia");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Alunos.Aluno", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Usuarios.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("MuscleUp.Dominio.Alunos.Aluno", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Exercicios.Exercicio", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Academias.Academia", "Academia")
                        .WithMany("Exercicios")
                        .HasForeignKey("IdAcademia")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Exercicios.ExercicioDoTreino", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Exercicios.Exercicio", "Exercicio")
                        .WithMany("ExerciciosDosTreinosVinculados")
                        .HasForeignKey("IdExercicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuscleUp.Dominio.GruposMuscularesTrabalhados.GrupoMuscularTrabalhado", "GrupoMuscularTrabalhado")
                        .WithMany("ExerciciosDoTreino")
                        .HasForeignKey("IdMembroTrabalhado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("GrupoMuscularTrabalhado");
                });

            modelBuilder.Entity("MuscleUp.Dominio.GruposMuscularesTrabalhados.GrupoMuscularTrabalhado", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Treinos.Treino", "Treino")
                        .WithMany("GruposMuscularesTrabalhados")
                        .HasForeignKey("IdTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Treinos.Treino", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Academias.Academia", "Academia")
                        .WithMany("Treinos")
                        .HasForeignKey("IdAcademia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuscleUp.Dominio.Alunos.Aluno", "Aluno")
                        .WithMany("Treinos")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MuscleUp.Dominio.Usuarios.Usuario", "Professor")
                        .WithMany("TreinosCriados")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Academia");

                    b.Navigation("Aluno");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Treinos.TreinoPublicoEDestinadoDoAluno", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Alunos.Aluno", "Aluno")
                        .WithMany("TreinosPublicosEDestinados")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuscleUp.Dominio.Usuarios.Usuario", "ProfessorQueDestinou")
                        .WithMany("TreinosMinistrados")
                        .HasForeignKey("IdProfessorQueDestinou")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MuscleUp.Dominio.Treinos.Treino", "Treino")
                        .WithMany("TreinosPublicosEDestinasdoDoAluno")
                        .HasForeignKey("IdTreino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("ProfessorQueDestinou");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Usuarios.Usuario", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Academias.Academia", "Academia")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdAcademia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Academia");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Academias.Academia", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Treinos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Alunos.Aluno", b =>
                {
                    b.Navigation("Treinos");

                    b.Navigation("TreinosPublicosEDestinados");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Exercicios.Exercicio", b =>
                {
                    b.Navigation("ExerciciosDosTreinosVinculados");
                });

            modelBuilder.Entity("MuscleUp.Dominio.GruposMuscularesTrabalhados.GrupoMuscularTrabalhado", b =>
                {
                    b.Navigation("ExerciciosDoTreino");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Treinos.Treino", b =>
                {
                    b.Navigation("GruposMuscularesTrabalhados");

                    b.Navigation("TreinosPublicosEDestinasdoDoAluno");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Usuarios.Usuario", b =>
                {
                    b.Navigation("Aluno");

                    b.Navigation("TreinosCriados");

                    b.Navigation("TreinosMinistrados");
                });
#pragma warning restore 612, 618
        }
    }
}
