// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuscleUp.DataBase;

#nullable disable

namespace MuscleUp.DataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521001006_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MuscleUp.Dominio.Alunos.Aluno", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int?>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("ProblemasMedicos")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Alunos.Aluno", b =>
                {
                    b.HasOne("MuscleUp.Dominio.Usuarios.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("MuscleUp.Dominio.Alunos.Aluno", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MuscleUp.Dominio.Usuarios.Usuario", b =>
                {
                    b.Navigation("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
